[workspace]
resolver = "2" # Add this line
members = [
    "crates/idp-core",
    "crates/idp-cli",
]

[workspace.dependencies]
# Central place for common dependencies
serde = { version = "1.0", features = ["derive"] }
