[package]
name = "idp-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
idp-core = { version = "0.1.0", path = "../idp-core" }
tokio = { version = "1.46.1", features = ["full"] }
