[package]
name = "idp-core"
version = "0.1.0"
edition = "2024"

[dependencies]
data-encoding = "2.9.0"
rand = "0.9.1"
ring = "0.17.14"
serde = { workspace = true, features = ["derive"] }
serde_yaml = "0.9.34"
tempfile = "3.20.0"
